create table if not exists souls (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  content text not null,
  file_name text not null,
  created_at timestamptz default now()
);

alter table souls enable row level security;
